import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";

const dataSource = fs.readFileSync(new URL("./data.js", import.meta.url), "utf8");
const catalogueSource = fs.readFileSync(new URL("./catalog-expansion.js", import.meta.url), "utf8");
const photoSource = fs.readFileSync(new URL("./recipe-photos.js", import.meta.url), "utf8");
const titleSource = fs.readFileSync(new URL("./title-catalog.js", import.meta.url), "utf8");
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(dataSource, sandbox);
vm.runInContext(catalogueSource, sandbox);
vm.runInContext(photoSource, sandbox);
vm.runInContext(titleSource, sandbox);

const { stages, skills, recipes, badges, collectionConfig } = sandbox.window.CHEFFU_DATA;
const skillIds = new Set(skills.map((skill) => skill.id));
const recipeIds = new Set(recipes.map((recipe) => recipe.id));
const sourcedPhotos = sandbox.window.CHEFFU_RECIPE_PHOTOS || {};
const titles = sandbox.window.CHEFFU_TITLE_CATALOG || [];
const titleIds = new Set(titles.map((title) => title.id));

assert.equal(stages.length, 8, "Roadmap must have eight stages");
assert.equal(recipeIds.size, recipes.length, "Recipe IDs must be unique");
assert.ok(recipes.length >= 377, "Roadmap should offer at least 377 missions");
assert.ok(skills.length >= 100, "The skill system must remain granular");
assert.ok(recipes.every((recipe) => recipe.steps.length >= 4), "Every mission needs at least four safe steps");
assert.ok(recipes.every((recipe) => recipe.guide && ["reviewed", "draft"].includes(recipe.guide.status)), "Every recipe must expose a reviewed or draft guide");
assert.ok(recipes.every((recipe) => recipe.guide.ingredients?.length && recipe.guide.equipment?.length && recipe.guide.reviewNote), "Every recipe guide must disclose ingredients, equipment, and review status");
assert.ok(recipes.every((recipe) => recipe.description && recipe.description.includes(recipe.name)), "Every dish needs a dish-specific description");
assert.ok(recipes.every((recipe) => recipe.skillIds.every((id) => skillIds.has(id))), "Every recipe skill must exist");
assert.ok(skills.every((skill) => recipes.some((recipe) => recipe.skillIds.includes(skill.id))), "Every micro-skill needs a practice dish");
for (const id of ["catalog-eggless-chocolate-mug-cake", "catalog-eggless-banana-bread", "catalog-chickpea-shakshuka"]) {
  const recipe = recipes.find((item) => item.id === id);
  assert.ok(recipe && !recipe.skillIds.includes("crack-egg"), `${id} must not be classified as an egg mission`);
}
assert.ok(stages.every((stage) => recipes.some((recipe) => recipe.stage === stage.id)), "Every stage needs recipes");
assert.ok(recipes.some((recipe) => recipe.region === "South India"), "South Indian path is required");
assert.ok(recipes.some((recipe) => recipe.region === "North India"), "North Indian path is required");
assert.ok(recipes.some((recipe) => recipe.protein >= 30), "Protein-forward missions are required");
assert.ok(badges.length >= 5, "Collectible loop is required");
assert.equal(collectionConfig.indiaStates.length, 28, "India collection must represent all 28 states");
assert.ok(collectionConfig.worldCountries.length >= 20, "World collection needs at least 20 countries");
assert.ok(collectionConfig.indiaStates.every((item) => recipeIds.has(item.dishId)), "Every Indian state needs a linked dish");
assert.ok(collectionConfig.worldCountries.every((item) => recipeIds.has(item.dishId)), "Every passport country needs a linked dish");
assert.ok(recipes.every((recipe) => recipe.photo || sourcedPhotos[recipe.id]), "Every recipe needs source-linked imagery");
assert.equal(Object.keys(sourcedPhotos).length, recipes.length, "Every recipe must use a researched image asset");
assert.ok(Object.values(sourcedPhotos).every((photo) => photo.url.startsWith("assets/recipes/") && photo.page), "Recipe images must be local and retain a source page");
assert.ok(Object.values(sourcedPhotos).every((photo) => {
  const file = new URL(`./${photo.url}`, import.meta.url);
  return fs.existsSync(file) && fs.statSync(file).size > 1000;
}), "Every recipe image file must exist and contain image data");
const photoManifest = JSON.parse(fs.readFileSync(new URL("./assets/recipes/manifest.json", import.meta.url), "utf8"));
assert.equal(photoManifest.total, recipes.length, "Recipe image manifest must cover the full catalogue");
assert.deepEqual(new Set(photoManifest.items.map((item) => item.recipeId)), recipeIds, "Recipe image manifest IDs must match recipe IDs");
assert.equal(titles.length, 100, "Collections must expose exactly 100 titles");
assert.equal(titleIds.size, titles.length, "Title IDs must be unique");
assert.ok(titles.every((title) => title.description && title.requirement && title.condition), "Every title needs flavour text and an unlock rule");
assert.ok(titles.filter((title) => title.condition.type === "skillXp").every((title) => skillIds.has(title.condition.value)), "Skill titles must reference real micro-skills");
assert.ok(titles.filter((title) => title.condition.type === "recipeCooks").every((title) => recipeIds.has(title.condition.value)), "Dish titles must reference real dishes");

const index = fs.readFileSync(new URL("./index.html", import.meta.url), "utf8");
const readme = fs.readFileSync(new URL("./README.md", import.meta.url), "utf8");
const appSource = fs.readFileSync(new URL("./app.js", import.meta.url), "utf8");
const styles = fs.readFileSync(new URL("./styles.css", import.meta.url), "utf8");
for (const screenshot of ["cheffu-home-desktop.png", "cheffu-cook-complete-desktop.png"]) {
  assert.ok(fs.existsSync(new URL(`./assets/screenshots/${screenshot}`, import.meta.url)), `README screenshot missing: ${screenshot}`);
  assert.ok(readme.includes(`assets/screenshots/${screenshot}`), `README must display screenshot: ${screenshot}`);
}
assert.ok(fs.existsSync(new URL("./assets/brand/cheffu-aanya-logo.png", import.meta.url)), "Cheffu must include the Aanya mascot logo asset");
assert.ok(index.includes("assets/brand/cheffu-aanya-logo.png"), "Header and app metadata must use the Aanya mascot logo");
assert.ok(fs.existsSync(new URL("./assets/aanya/welcome.png", import.meta.url)), "Aanya welcome asset missing");
assert.ok(appSource.includes('const image = "assets/aanya/variations/proud-plating.jpg?v=3"'), "Home must use one fixed Aanya variation");
assert.ok(!appSource.includes("sceneImages") && !appSource.includes("AANYA_VARIATION_IMAGES") && !appSource.includes("aanyaCycle"), "Home must not cycle Aanya variations");
assert.ok(appSource.includes("aanyaHomePanel") && appSource.includes("Aanya's idea for you"), "Home must include one reactive Aanya recommendation");
assert.ok(appSource.includes("AANYA'S PICK") && appSource.includes("Aanya recommends"), "The quest card must visibly identify Aanya as its recommender");
assert.ok(appSource.includes("quest-swipe-card") && appSource.includes("data-pass-daily-quest") && appSource.includes("data-accept-daily-quest"), "Home must expose one swipeable Aanya suggestion with accessible action buttons");
assert.ok(appSource.includes("dailyQuestDeck") && appSource.includes("ANOTHER IDEA") && appSource.includes("COOK THIS"), "Aanya's suggestion deck must have clear left and right outcomes");
assert.ok(appSource.includes('addEventListener("pointerdown"') && appSource.includes('event.key === "ArrowRight"'), "Aanya suggestions must support touch, pointer, and keyboard input");
assert.ok(appSource.includes("SKILL TO TRAIN") && appSource.includes("COOKING REWARD"), "Each suggestion card must connect the dish to its skill and reward");
assert.ok(!appSource.includes('<section class="daily-card">'), "Home must not duplicate Aanya's recommendation in a separate daily card");
assert.ok(!appSource.includes("Two side quests") && !appSource.includes("picks.slice(1)"), "Home must show one recommendation card at a time");
assert.ok(appSource.includes("homeRouteHub") && appSource.includes("Your next moves"), "Home must link to the other main pages with contextual prompts");
assert.ok(appSource.includes("navNotificationCount") && appSource.includes("markRouteSeen") && appSource.includes("navSeen"), "Navigation notices must track pending page actions and clear after a visit");
assert.equal((index.match(/class="nav-notification"/g) || []).length, 4, "Each non-home navigation item needs a notification badge");
assert.ok(styles.includes(".home-route-grid") && styles.includes(".nav-notification[hidden]"), "Home shortcuts and navigation badges need responsive styling");
assert.ok(styles.includes(".quest-swipe-card") && styles.includes("touch-action: pan-y") && styles.includes("quest-accept-out"), "The quest deck needs responsive swipe styling and feedback");
const aanyaVariationFiles = fs.readdirSync(new URL("./assets/aanya/variations/", import.meta.url)).filter((file) => file.endsWith(".jpg"));
assert.equal(aanyaVariationFiles.length, 12, "Aanya expression deck must contain 12 additional poses");
assert.ok(!appSource.includes("data-aanya-pose") && !appSource.includes("data-aanya-cycle") && !appSource.includes("More moods"), "Aanya commentary must not expose manual mood choices");
assert.ok(!/Ayyo|Seri/.test(appSource), "Aanya's dialogue must use a friendly, region-neutral voice");
assert.ok(!appSource.includes("TODAY'S 1× QUEST") && appSource.includes("AANYA'S PICK"), "Daily recommendation wording must stay clear");
assert.ok(index.includes('class="settings-diet"') && !index.includes('class="topbar-diet"'), "Diet preference must live in Settings instead of the top bar");
assert.ok(appSource.includes("function availableSkills") && appSource.includes("function eligibleMapItems"), "Diet preference must filter Skills and recipe-linked Collections");
assert.ok(appSource.includes("isDietLockedSkill") && styles.includes(".skill-system-node.is-diet-locked"), "Veg users must see Eggs & Protein as a locked skill-tree branch");
assert.ok(appSource.includes('id="dishes-search"') && appSource.includes("Browse all dishes"), "Dishes must expose a searchable recipe library");
assert.ok(!appSource.includes("Do the action. Then tap when your hands are safe."), "Recipe checklist heading must avoid the removed safety-action line");
assert.ok(!dataSource.includes("Boot Sequence") && dataSource.includes("Kitchen First Steps"), "Beginner roadmap wording must use plain language");
assert.ok(!styles.includes('.nav-item[data-route="dishes"]'), "Dishes navigation must not have a special highlight");
assert.ok(fs.existsSync(new URL("./assets/brand/cheffu-wordmark.png", import.meta.url)), "Cheffu must include the illustrated wordmark");
assert.ok(index.includes("assets/brand/cheffu-wordmark.png"), "Header must use the illustrated Cheffu wordmark");
for (const file of ["styles.css", "data.js", "catalog-expansion.js", "recipe-photos.js", "title-catalog.js", "app.js"]) {
  assert.ok(index.includes(file), `index.html must load ${file}`);
}
assert.ok(appSource.includes("renderSkillTree"), "Skills page must keep its connected tree view");
assert.ok(appSource.includes("clusterStyles"), "Skill systems must remain colour-coded");
assert.ok(appSource.includes("renderCollections"), "Collections page must remain available");
assert.ok(appSource.includes("checkpointXpForStep"), "Recipe checkpoints must award partial XP");
assert.ok(appSource.includes('"1": "dishes"') && appSource.includes('"3": "home"') && appSource.includes('"5": "roadmap"'), "Five navigation hotkeys must follow visual order");
assert.ok(index.includes('class="nav-icon"') && !index.includes(">⚡<") && !index.includes(">⌁<"), "Skills and Roadmap must use monochrome navigation icons");
assert.ok(!appSource.includes("All diets"), "Diet lanes must stay visible instead of using an All diets option");
assert.ok(appSource.includes("equippedTitleId") && appSource.includes("renderTitleVault"), "Titles must be unlockable and equippable in Collections");
assert.ok(appSource.includes("playerName") && appSource.includes("openNameDialog"), "Player name must be requested and saved locally");
assert.ok(index.includes("What do you eat?") && appSource.includes("renderOnboardingDietFilter"), "First-time setup must collect dietary preference");
assert.ok(appSource.includes("Guided recipe") && appSource.includes("Technique mission"), "Recipe completeness must be visible before a cook starts");
assert.ok(index.includes("viewport-fit=cover"), "Mobile viewport must support device safe areas");
assert.ok(index.includes('rel="manifest"') && index.includes("og:title"), "Production metadata and install manifest must be present");
assert.ok(appSource.includes("downloadProgressBackup") && appSource.includes("restoreProgressBackup"), "Local-first progress must support private backup and restore");
assert.ok(appSource.includes("serviceWorker.register"), "The app shell must register its offline worker on HTTPS");
assert.ok(fs.existsSync(new URL("./manifest.webmanifest", import.meta.url)) && fs.existsSync(new URL("./service-worker.js", import.meta.url)), "PWA install and offline assets must exist");
const rootFiles = fs.readdirSync(new URL("./", import.meta.url));
assert.ok(!rootFiles.some((file) => /\.(png|jpe?g|webp)$/i.test(file)), "Raster images must live under assets, not in the repository root");
assert.ok(!rootFiles.some((file) => /(?:PRD|PROMPT)/i.test(file)), "Planning and generation prompt files must stay out of the production repository");
assert.ok(!rootFiles.includes("vercel.json"), "Hosting-specific Vercel configuration must stay out of the repository");
assert.ok(styles.includes("--tap-target: 44px") && styles.includes("safe-area-inset-bottom"), "Mobile controls must retain 44px targets and safe-area spacing");
assert.ok(styles.includes("--brand-cream: #fcf5e7") && styles.includes(".topbar #settings-button") && styles.includes("width: min(calc(100% - 32px), var(--content))"), "Header must be contained and visually match the Cheffu wordmark");
assert.ok(appSource.includes("handleTopbarScroll") && styles.includes(".topbar.is-hidden"), "Header must hide on downward scrolling and return on upward scrolling");
assert.ok(appSource.includes('cookDialog.classList.add("is-complete")') && styles.includes(".sheet.is-complete") && styles.includes("object-fit: contain"), "Cook completion must use a roomy responsive celebration layout");
assert.ok(styles.includes("overflow-x: clip") && styles.includes("@media (max-width: 700px)"), "Mobile layout must prevent page overflow and keep its phone breakpoint");
assert.ok(appSource.includes('let skillView = "tree"'), "Skills must show the connected tree by default on every device");
const guidedTrackIds = ["morning", "dal-legume", "veg-curry", "rice-onepot", "family-meals", "plant-protein-fast", "plant-protein-meals", "egg-meat-protein", "one-pot", "dough", "south-tiffin", "south-meals", "north", "west", "east-ne", "sweet", "pan-asian", "italian", "world-foundations", "world-showpieces"];
assert.ok(guidedTrackIds.every((id) => appSource.includes(`id: "${id}"`)), "Roadmap must retain all 20 focused guided paths");

const reviewedGuides = recipes.filter((recipe) => recipe.guide.status === "reviewed").length;
const draftGuides = recipes.length - reviewedGuides;
console.log(`Verified ${recipes.length} recipe records (${reviewedGuides} reviewed guides, ${draftGuides} drafts), ${skills.length} skills, ${stages.length} stages, ${badges.length} badges, and ${titles.length} titles.`);
